=== webasyst/webasyst-framework/wa-data/protected/wa-installer/backup/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*, settings?, thumbs?, locales?)>
<!ATTLIST theme
    id CDATA #REQUIRED
    system (1|0) "0"
    vendor CDATA #IMPLIED
    author CDATA #IMPLIED
    app CDATA #REQUIRED
    parent_theme_id CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
    locale CDATA #REQUIRED
>
<!-- Theme's files list available for editing -->
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file
    path CDATA #REQUIRED
    custom (1|0) "0"
    parent (1|0) "0"
    modified (1|0) "0"
>
<!-- THeme usage hints and instructions -->
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
    locale CDATA #REQUIRED
>
<!--Theme settings-->
<!ELEMENT settings (setting+)>
<!ELEMENT setting (value+,filename?,name+,description*,options?)>

<!ATTLIST setting
    var CDATA #REQUIRED
    control_type (text|select|checkbox|radio|color|image|image_select) "text"
>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    locale CDATA #IMPLIED
>

<!ELEMENT filename (#PCDATA)>
<!ELEMENT options (option+)>
<!ELEMENT option (name*,description*)>
<!ATTLIST option
    value CDATA #IMPLIED
>
<!--List of allowed thumb sizes-->
<!ELEMENT thumbs (thumb*)>
<!ELEMENT thumb (#PCDATA)>

<!--Theme strings-->
<!ELEMENT locales (locale+)>
<!ELEMENT locale (msgid,msgstr+)>
<!ELEMENT msgid (#PCDATA)>
<!ELEMENT msgstr (#PCDATA)>
<!ATTLIST msgstr
    locale CDATA #REQUIRED
>

=== webasyst/webasyst-framework/wa-apps/site/themes/vk/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="vk" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.1.29">
    <name locale="en_US">VK</name>
    <name locale="ru_RU">Вконтакте</name>
    <description locale="ru_RU">Ваш сайт во «Вконтакте» в виде Iframe-приложения.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the VK theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства VK</description>
        </file>
        <file path="vk.css" custom="0">
            <description locale="en_US">Core CSS of the VK theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна VK</description>
        </file>
        <file path="vk.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>VK</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://vk.com">VK.com</a> social network as iframe apps. VK theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the VK (i.e. this) theme for the Site application. All VK design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p>Темы <b>VK</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в соцсеть «<a href="http://vk.com">Вконтакте</a>» в виде iframe-приложений. Семейство тем VK универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт» (данная тема). Все темы VK для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>
    <settings>
        <setting var="vk_app_id" control_type="text">
            <value>YOUR_VK_APP_ID</value>
            <name locale="en_US">VK App ID</name>
            <name locale="ru_RU">ID приложения «Вконтакте»</name>
            <description locale="en_US"></description>
            <description locale="ru_RU"><![CDATA[Для встраивания сайта в соцсеть в виде приложения необходимо создать приложение для «Вконтакте». Инструкция: <a href="http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/" target="_blank">http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/</a>]]></description>
        </setting>
        <setting var="vk_app_secret" control_type="text">
            <value>YOUR_VK_APP_SECRET</value>
            <name locale="en_US">VK App Secret</name>
            <name locale="ru_RU">Защищенный ключ приложения «Вконтакте»</name>
            <description locale="en_US"></description>
            <description locale="ru_RU"><![CDATA[Для встраивания сайта в соцсеть в виде приложения необходимо создать приложение для «Вконтакте». Инструкция: <a href="http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/" target="_blank">http://www.webasyst.ru/help/27/shop-script-5-vkontakte-online-store/</a>]]></description>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-data/protected/wa-installer/backup/wa-content/xml/example/wa-app-theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd" >
<theme id="my-theme" system="0" vendor="webasyst" author="Webasyst" app="my-app" version="1.0.0">
	<name locale="en_US"><![CDATA[Theme name]]></name>
	<name locale="ru_RU"><![CDATA[Название темы]]></name>
	<description locale="en_US"><![CDATA[Theme name description]]></description>
	<description locale="ru_RU"><![CDATA[Описание "название темы"]]></description>
	<files>
		<file path="index.html" custom="0">
			<description locale="en_US"><![CDATA[Primary file]]></description>
			<description locale="ru_RU"><![CDATA[Основной файл]]></description>
		</file>
	</files>
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/nifty/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="nifty" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.2.17">
    <name locale="en_US">Nifty</name>
    <name locale="ru_RU">Nifty</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Nifty theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Nifty</description>
        </file>
        <file path="nifty.css" custom="0">
            <description locale="en_US">Core CSS of the Nifty theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Nifty</description>
        </file>
        <file path="nifty.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal storefront navigation</description>
            <description locale="ru_RU">Внутренняя навигация по витрине магазина</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>Nifty</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Nifty (i.e. this) theme for the Site application. All Nifty design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Nifty design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p><b>Nifty</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Nifty для приложения «Сайт» (данная тема). Все темы дизайна Nifty для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Nifty оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <settings>
        <setting var="color_scheme" control_type="select">
            <value>purple</value>
            <name locale="ru_RU">Цветовая гамма</name>
            <name locale="en_US">Color scheme</name>
            <options>
                <option value="purple">
                    <name locale="ru_RU">Фиолетовая</name>
                    <name locale="en_US">Purple</name>
                </option>
                <option value="green">
                    <name locale="ru_RU">Зеленая</name>
                    <name locale="en_US">Green</name>
                </option>
                <option value="blue">
                    <name locale="ru_RU">Синяя</name>
                    <name locale="en_US">Blue</name>
                </option>
                <option value="red">
                    <name locale="ru_RU">Красная</name>
                    <name locale="en_US">Red</name>
                </option>
                <option value="yellow">
                    <name locale="ru_RU">Желтая</name>
                    <name locale="en_US">Yellow</name>
                </option>
                <option value="white">
                    <name locale="ru_RU">Белая</name>
                    <name locale="en_US">White</name>
                </option>
                <option value="black">
                    <name locale="ru_RU">Черная</name>
                    <name locale="en_US">Black</name>
                </option>
            </options>
        </setting>
        <setting var="facebook_url" control_type="text">
            <value>#</value>
            <name locale="en_US">Facebook Page URL</name>
            <name locale="ru_RU">Адрес страницы в Фейсбуке</name>
        </setting>
        <setting var="twitter_url" control_type="text">
            <value>#</value>
            <name locale="en_US">Twitter URL</name>
            <name locale="ru_RU">Адрес страницы на Твиттере</name>
        </setting>
        <setting var="ajax_filters" control_type="checkbox">
            <value>1</value>
            <name locale="en_US">AJAX-enabled product by-feature filtering</name>
            <name locale="ru_RU">AJAX-фильтры товаров по характеристикам</name>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-data/public/mailer/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="1" vendor="webasyst" author="Webasyst" app="mailer" parent_theme_id="site:default" version="2.1.0">
    <name locale="en_US">Default 2.0</name>
    <name locale="ru_RU">Дефолт 2.0</name>
    <files>
        <file path="my.subscriptions.html">
            <description locale="en_US">Subscriptions home page</description>
            <description locale="ru_RU">Начальная страница подписок</description>
        </file>

        <file path="my.nav.html">
            <description locale="en_US">Customer portal interface: сommon navigation elements</description>
            <description locale="ru_RU">Личный кабинет клиента: общие элементы навигации</description>
        </file>

        <file path="index.html" custom="0" parent="1"></file>
        <file path="error.html" custom="0" parent="1"></file>
    </files>
</theme>
