=== webasyst/webasyst-framework/wa-data/protected/wa-installer/backup/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*, settings?, thumbs?, locales?)>
<!ATTLIST theme
    id CDATA #REQUIRED
    system (1|0) "0"
    vendor CDATA #IMPLIED
    author CDATA #IMPLIED
    app CDATA #REQUIRED
    parent_theme_id CDATA #IMPLIED
    version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name
    locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
    locale CDATA #REQUIRED
>
<!-- Theme's files list available for editing -->
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file
    path CDATA #REQUIRED
    custom (1|0) "0"
    parent (1|0) "0"
    modified (1|0) "0"
>
<!-- THeme usage hints and instructions -->
<!ELEMENT about (#PCDATA)>
<!ATTLIST about
    locale CDATA #REQUIRED
>
<!--Theme settings-->
<!ELEMENT settings (setting+)>
<!ELEMENT setting (value+,filename?,name+,description*,options?)>

<!ATTLIST setting
    var CDATA #REQUIRED
    control_type (text|select|checkbox|radio|color|image|image_select) "text"
>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
    locale CDATA #IMPLIED
>

<!ELEMENT filename (#PCDATA)>
<!ELEMENT options (option+)>
<!ELEMENT option (name*,description*)>
<!ATTLIST option
    value CDATA #IMPLIED
>
<!--List of allowed thumb sizes-->
<!ELEMENT thumbs (thumb*)>
<!ELEMENT thumb (#PCDATA)>

<!--Theme strings-->
<!ELEMENT locales (locale+)>
<!ELEMENT locale (msgid,msgstr+)>
<!ELEMENT msgid (#PCDATA)>
<!ELEMENT msgstr (#PCDATA)>
<!ATTLIST msgstr
    locale CDATA #REQUIRED
>

=== webasyst/webasyst-framework/wa-apps/site/themes/sidebar/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="sidebar" system="0" vendor="webasyst" author="Webasyst" app="site" version="2.1.17">
    <name locale="en_US">Sidebar 2.0</name>
    <name locale="ru_RU">Sidebar 2.0</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Sidebar theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Sidebar</description>
        </file>
        <file path="sidebar.css" custom="0">
            <description locale="en_US">Core CSS of the Sidebar theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Sidebar</description>
        </file>
        <file path="sidebar.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="nav.sidebar.html" custom="0">
            <description locale="en_US">Internal app navigation tree</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>Sidebar 2.0</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Sidebar (i.e. this) theme for the Site application. All Sidebar design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Sidebar design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p><b>Sidebar 2.0</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Sidebar для приложения «Сайт» (данная тема). Все темы дизайна Sidebar для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Sidebar оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <settings>
        <setting var="logo" control_type="image">
            <value></value>
            <filename>img/logo.*</filename>
            <name locale="en_US">Logo</name>
            <name locale="ru_RU">Логотип</name>
        </setting>
        <setting var="sidebar_unfolded_nav" control_type="checkbox">
            <value>1</value>
            <name locale="en_US">Automatically unfold sidebar navigation tree</name>
            <name locale="ru_RU">Автоматически разворачивать дерево навигации в боковой панели</name>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.3.19">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <description locale="en_US">Theme for mobile devices</description>
    <description locale="ru_RU">Тема для мобильных устройств</description>
    <files>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of theme</description>
            <description locale="ru_RU">Индексный шаблон темы</description>
        </file>
        <file path="layout-head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="layout-header.html" custom="0">
            <description locale="en_US">App specific header content</description>
            <description locale="ru_RU">Содержимое «шапки» приложения</description>
        </file>
        <file path="layout-menu.html" custom="0">
            <description locale="en_US">App hidden menu content</description>
            <description locale="ru_RU">Содержимое «скрытого меню» приложения</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout for Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Личный кабинет: редактирование контактной информации</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="mobile.css" custom="0">
            <description locale="en_US">General CSS for Site Application</description>
            <description locale="ru_RU">Основные стили для приложения "Сайт"</description>
        </file>
        <file path="mobile.js" custom="0">
            <description locale="en_US">General JavaScript for Site Application</description>
            <description locale="ru_RU">Основные скрипты для приложения "Сайт"</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
]]>
    </about>
    <settings>
        <setting var="logo" control_type="image">
            <value></value>
            <filename>img/logo.*</filename>
            <name locale="en_US">Slide-out menu logo</name>
            <name locale="ru_RU">Логотип в боковой панели</name>
            <description locale="en_US">PNG with alpha channel. Logo is displayed in the slide-out menu.</description>
            <description locale="ru_RU">PNG с прозрачностью. Логотип отображается в боковой панели.</description>
        </setting>
        <setting var="pagination" control_type="select">
            <value>lazyloading</value>
            <name locale="en_US">Displaying of long product lists</name>
            <name locale="ru_RU">Отображение длинных списков товаров</name>
            <description locale="ru_RU">Применяется к спискам товаров в категориях и результатах поиска.</description>
            <description locale="en_US">For category-listing pages and search results.</description>
            <options>
                <option value="lazyloading">
                    <name locale="ru_RU">Автоматически загружать содержимое при прокручивании страницы</name>
                    <name locale="en_US">Automatically load content on page scrolling</name>
                </option>
                <option value="paging">
                    <name locale="ru_RU">Постраничная навигация (1 2 3 4)</name>
                    <name locale="en_US">Paginated lists (1 2 3 4)</name>
                </option>
            </options>
        </setting>
        <setting var="show_full_site_link" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Отображать ссылку на полную версию сайта</name>
            <name locale="en_US">Display a link to the full version of the site</name>
            <description locale="ru_RU">Ссылку показывается в боковой панели.
            </description>
            <description locale="en_US">The link will be displayed in the bottom of the slide-out menu.
            </description>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
        <setting var="show_cart" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать корзину покупок</name>
            <name locale="en_US">Show shopping cart</name>
            <description locale="ru_RU">Корзина будет показана, если на сайте настроена хотя бы одна витрина интернет-магазина Shop-Script.</description>
            <description locale="en_US">The shopping cart will be shown if at least one Shop-Script storefront is set up on the website.</description>
        </setting>
    </settings>
    <locales>
        <locale>
            <msgid>Follow us</msgid>
            <msgstr locale="ru_RU">Подписаться на новости</msgstr>
        </locale>
        <locale>
            <msgid>Subscribe to our email newsletter</msgid>
            <msgstr locale="ru_RU">Подписаться на рассылку</msgstr>
        </locale>
        <locale>
            <msgid>Or follow us on Facebook and Twitter</msgid>
            <msgstr locale="ru_RU">Или подписывайтесь в соцсетях</msgstr>
        </locale>
        <locale>
            <msgid>Editors’ choice</msgid>
            <msgstr locale="ru_RU">Избранное</msgstr>
        </locale>
        <locale>
            <msgid>All photos</msgid>
            <msgstr locale="ru_RU">Все фотографии</msgstr>
        </locale>
        <locale>
            <msgid>Information</msgid>
            <msgstr locale="ru_RU">Информация</msgstr>
        </locale>
        <locale>
            <msgid>Hub</msgid>
            <msgstr locale="ru_RU">Хаб</msgstr>
        </locale>
        <locale>
            <msgid>Desktop version</msgid>
            <msgstr locale="ru_RU">Полная версия</msgstr>
        </locale>
    </locales>
</theme>

=== webasyst/webasyst-framework/wa-data/public/site/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="0" vendor="webasyst" author="Webasyst" app="site" version="2.0.1" parent_theme_id="shop:default">
    <name locale="en_US">Default 2.0</name>
    <name locale="ru_RU">Дефолт 2.0</name>
    <description locale="en_US">Adaptive design theme for all base Webasyst apps</description>
    <description locale="ru_RU">Семейство адаптивных тем дизайна для всех базовых приложений Webasyst</description>
    <files>
        <file path="index.html" custom="0" modified="1">
    		<description locale="en_US">Core layout of the Default theme family</description>
    		<description locale="ru_RU"></description>
        </file>
        <file path="default.css" custom="0" modified="1">
    		<description locale="en_US">Core CSS of the Default theme family</description>
    		<description locale="ru_RU"/>
        </file>
        <file path="default.colors.css" custom="0">
    		<description locale="en_US">Default theme color schemes</description>
    		<description locale="ru_RU">Цветовые схемы темы дизайна «Дефолт»</description>
        </file>
        <file path="default.mobile.css" custom="0">
    		<description locale="en_US">Additional CSS for multi-touch mobile devices</description>
    		<description locale="ru_RU">Дополнительный CSS для мобильных устройств</description>
        </file>
        <file path="default.tablet.css" custom="0">
    		<description locale="en_US">Additional CSS for tablet computers (e.g. iPad)</description>
    		<description locale="ru_RU">Дополнительный CSS для планшетных компьютеров (например, iPad)</description>
        </file>
        <file path="default.wide.css" custom="0">
    		<description locale="en_US">Additional CSS for wide-screen devices</description>
    		<description locale="ru_RU">Дополнительный CSS для устройств с широким экраном</description>
        </file>
        <file path="default.js" custom="0">
    		<description locale="en_US">JS</description>
    		<description locale="ru_RU">JS</description>
        </file>
    	<file path="main.html" custom="0">
    		<description locale="en_US">Main layout for the Site app content</description>
    		<description locale="en_US">Основной вывод приложения «Сайт»</description>
    	</file>
    	<file path="head.html" custom="0">
    		<description locale="en_US">Site app's &lt;head&gt; instructions</description>
    		<description locale="en_US">Блок &lt;head&gt; приложения «Сайт»</description>
    	</file>
    	<file path="footer.html" custom="0">
    		<description locale="en_US">App specific footer content</description>
    		<description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
    		<description locale="en_US">Internal app search form</description>
    		<description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="page.html" custom="0">
    		<description locale="en_US">Static page content and navigation</description>
    		<description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
    		<description locale="en_US">Login page</description>
    		<description locale="ru_RU">Страница входа для пользователей</description>
    	</file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
    		<description locale="en_US">404 and other errors</description>
    		<description locale="ru_RU">404 и другие ошибки</description>
        </file>
    <file path="my.profile.html" custom="1" modified="1"/></files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default (i.e. this) theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <settings>
        <setting var="logo" control_type="image">
            <value/>
            <filename>img/logo.*</filename>
            <name locale="en_US">Company Logo</name>
            <name locale="ru_RU">Логотип компании</name>
        </setting>
        <setting var="banner_caption" control_type="text">
            <value>Пчелкин дом</value>
            
            <name locale="en_US">Site-wide banner caption</name>
            <name locale="ru_RU">Заголовок на основном баннере</name>
        </setting>
        <setting var="color_scheme" control_type="image_select">
            <value>img/backgrounds/themesettings/blue.png</value>
            <name locale="ru_RU">Цветовая гамма</name>
            <name locale="en_US">Color scheme</name>
            <options>
                <option value="img/backgrounds/themesettings/green.png"/>
                <option value="img/backgrounds/themesettings/blue.png"/>
                <option value="img/backgrounds/themesettings/red.png"/>
                <option value="img/backgrounds/themesettings/yellow.png"/>
            </options>
        </setting>
        <setting var="custom_background" control_type="image">
            <value/>
            <filename>img/custom_background.*</filename>
            <name locale="en_US">Custom background</name>
            <name locale="ru_RU">Свое фоновое изображение</name>
        </setting>
        <setting var="page_nav_mode" control_type="radio">
            <value>slidemenu</value>
            <name locale="ru_RU">Меню навигации</name>
            <name locale="en_US">Navigation menu</name>
            <options>
                <option value="slidemenu">
                    <name locale="ru_RU">Прокручивающееся (waSlideMenu)</name>
                    <name locale="en_US">Slide menu (waSlideMenu)</name>
                    <description locale="ru_RU">Рекомендуется для многоуровневых навигационных меню, в которых на каждом уровне примерно одинаковое количество элементов-ссылок</description>
                    <description locale="en_US">Great for multi-level menus with relatively equal number of elements on each navigation level</description>
                </option>
                <option value="dropdown">
                    <name locale="ru_RU">Выпадающее</name>
                    <name locale="en_US">Drop down menu</name>
                    <description locale="ru_RU">Классическое выпадающее меню</description>
                    <description locale="en_US">Classic drop down menu</description>
                </option>
            </options>
        </setting>
        <setting var="facebook" control_type="text">
            <value>http://</value>
            <name locale="en_US">Facebook page URL</name>
            <name locale="ru_RU">Адрес страницы во «Фейсбуке»</name>
        </setting>
        <setting var="twitter" control_type="text">
            <value>username</value>
            <name locale="en_US">Twitter username</name>
            <name locale="ru_RU">Имя пользователя в Твиттере</name>
            <description locale="en_US">Example: webasyst</description>
            <description locale="ru_RU">Например: webasyst_ru</description>
        </setting>
        <setting var="vk" control_type="text">
            <value>http://</value>
            <name locale="en_US">VK.com page URL</name>
            <name locale="ru_RU">Адрес страницы или группы во «ВКонтакте»</name>
        </setting>
        <setting var="followus_leash" control_type="checkbox">
            <value>1</value>
            <name locale="en_US">Follow us sticky block</name>
            <name locale="ru_RU">Блок «Подписаться на новости»</name>
        </setting>
    </settings>
    <locales>
        <locale>
            <msgid>Follow us</msgid>
            <msgstr locale="ru_RU">Подписаться на новости</msgstr>
        </locale>
        <locale>
            <msgid>Subscribe to our email newsletter</msgid>
            <msgstr locale="ru_RU">Подписаться на рассылку</msgstr>
        </locale>
        <locale>
            <msgid>Or follow us on Facebook and Twitter</msgid>
            <msgstr locale="ru_RU">Или подписывайтесь в соцсетях</msgstr>
        </locale>
    </locales>
</theme>
