=== webasyst/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*)>
<!ATTLIST theme 
	id CDATA #REQUIRED
	system (1|0) "0"
	vendor CDATA #IMPLIED
	author CDATA #IMPLIED
	app CDATA #REQUIRED
	parent_theme_id CDATA #IMPLIED
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 
	locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description 
	locale CDATA #REQUIRED
>
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file 
	path CDATA #REQUIRED
	custom (1|0) "0"
	parent (1|0) "0"
>
<!ELEMENT about (#PCDATA)>
<!ATTLIST about 
	locale CDATA #REQUIRED
>

=== webasyst/webasyst-framework/wa-apps/site/themes/facebook/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="facebook" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.2.18">
    <name locale="en_US">Facebook</name>
    <name locale="ru_RU">Фейсбук</name>
    <description locale="ru_RU">Ваш сайт внутри Фейсбука в виде iframe-приложения.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Facebook theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Facebook</description>
        </file>
        <file path="facebook.css" custom="0">
            <description locale="en_US">Core CSS of the Facebook theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Facebook</description>
        </file>
        <file path="facebook.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
<p><b>Facebook</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://www.facebook.com">Facebook</a> social network as iframe apps. Facebook theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Facebook (i.e. this) theme for the Site application. All Facebook design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
<p>Темы <b>Facebook</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в «<a href="http://www.facebook.com">Фейсбук</a>» в виде iframe-приложений. Семейство тем Facebook универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт» (данная тема). Все темы Facebook для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>
    <settings>
        <setting var="facebook_app_id" control_type="text">
            <value>YOUR_FACEBOOK_APP_ID</value>
            <name locale="en_US">Facebook App ID</name>
            <name locale="ru_RU">Идентификатор Facebook-приложения</name>
            <description locale="en_US"><![CDATA[To embed your site into Facebook as an app you need to create a Facebook app. Follow the guide: <a href="http://www.webasyst.com/help/55/shop-script-5-facebook-online-store/" target="_blank">http://www.webasyst.com/help/55/shop-script-5-facebook-online-store/</a>]]></description>
            <description locale="ru_RU"><![CDATA[Для встраивания сайта в соцсеть в виде приложения необходимо создать Facebook-приложение. Инструкция: <a href="http://www.webasyst.ru/help/30/shop-script-5-facebook-online-store/" target="_blank">http://www.webasyst.ru/help/30/shop-script-5-facebook-online-store/</a>]]></description>
        </setting>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
    </settings>
</theme>

=== webasyst/webasyst-framework/wa-apps/photos/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="0" vendor="webasyst" author="Webasyst" app="photos" parent_theme_id="site:default" version="4.0.0">
    <name locale="en_US">Default 4.0</name>
    <name locale="ru_RU">Дефолт 4.0</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" parent="1">
        </file>
        <file path="default.css" parent="1">
        </file>
        <file path="default.photos.css">
        </file>
        <file path="default.photos.js">
        </file>
        <file path="head.html">
            <description locale="en_US">Photos app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Фото»</description>
        </file>
        <file path="header.html">
            <description locale="en_US">App specific header content</description>
            <description locale="ru_RU">Содержимое «шапки» приложения</description>
        </file>
        <file path="main.html">
            <description locale="en_US">Main layout and navigation for the Photos app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Фото»</description>
        </file>
        <file path="footer.html">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="photos-thumbs.html">
            <description locale="en_US">Photo list thumbnails view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="photos-plain.html">
            <description locale="en_US">Photo list plain view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="photo.html">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="home.html">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="album.html">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="search.html">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>
        <file path="page.html">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="default.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>
    <thumbs>
        <thumb>200x0</thumb>
        <thumb>970x0</thumb>
    </thumbs>
</theme>

=== webasyst/webasyst-framework/wa-content/xml/example/wa-app-theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd" >
<theme id="my-theme" system="0" vendor="webasyst" author="Webasyst" app="my-app" version="1.0.0">
	<name locale="en_US"><![CDATA[Theme name]]></name>
	<name locale="ru_RU"><![CDATA[Название темы]]></name>
	<description locale="en_US"><![CDATA[Theme name description]]></description>
	<description locale="ru_RU"><![CDATA[Описание "название темы"]]></description>
	<files>
		<file path="index.html" custom="0">
			<description locale="en_US"><![CDATA[Primary file]]></description>
			<description locale="ru_RU"><![CDATA[Основной файл]]></description>
		</file>
	</files>
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="default" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:default" version="2.2.1">
    <name locale="en_US">Default 2.0</name>
    <name locale="ru_RU">Дефолт 2.0</name>
    <files>
        <file path="index.html" parent="1">
        </file>
        <file path="default.css" parent="1">
        </file>
        <file path="default.blog.js" custom="0">
        </file>         
        <file path="default.blog.css" custom="0">
        </file>      
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="header.html" custom="0">
    		<description locale="en_US">App specific header content</description>
    		<description locale="ru_RU">Содержимое «шапки» приложения</description>
    	</file>
    	<file path="banner.html" custom="0">
    		<description locale="en_US">App specific banner content</description>
    		<description locale="ru_RU">Контент в области баннера</description>
    	</file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
    	<file path="footer.html">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="post.album.html" custom="0">
            <description locale="en_US">Photo album attached to the blog post</description>
            <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="default.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Default</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Default theme for the Site application. All Default design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Default design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Default</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Default для приложения «Сайт» (данная тема). Все темы дизайна Default для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Default оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>    
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/facebook/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="facebook" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:facebook" version="1.1.3">
    <name locale="en_US">Facebook</name>
    <name locale="ru_RU">Facebook</name>
    <files>
        <file path="facebook.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal app navigation</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="facebook.css" custom="0" parent="1">
        </file>
        <file path="facebook.js" custom="0" parent="1">
        </file>
        <file path="facebook.blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Facebook</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://www.facebook.com">Facebook</a> social network as iframe apps. Facebook theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Facebook theme for the Site application. All Facebook design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p>Темы <b>Facebook</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в «<a href="http://www.facebook.com">Фейсбук</a>» в виде iframe-приложений. Семейство тем Facebook универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт». Все темы Facebook для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>    
</theme>
