=== webasyst/webasyst-framework/wa-content/xml/wa-app-theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT theme (name+,description*,files*,about*)>
<!ATTLIST theme 
	id CDATA #REQUIRED
	system (1|0) "0"
	vendor CDATA #IMPLIED
	author CDATA #IMPLIED
	app CDATA #REQUIRED
	parent_theme_id CDATA #IMPLIED
	version CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 
	locale CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description 
	locale CDATA #REQUIRED
>
<!ELEMENT files (file+)>
<!ELEMENT file (description*)>
<!ATTLIST file 
	path CDATA #REQUIRED
	custom (1|0) "0"
	parent (1|0) "0"
>
<!ELEMENT about (#PCDATA)>
<!ATTLIST about 
	locale CDATA #REQUIRED
>

=== webasyst/webasyst-framework/wa-apps/photos/themes/mobile/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="mobile" system="0" vendor="webasyst" author="Webasyst" app="photos" parent_theme_id="site:mobile" version="1.0.0">
    <name locale="en_US">Mobile</name>
    <name locale="ru_RU">Mobile</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="album.html" custom="0">
            <description locale="en_US">Wrapper for photo album</description>
            <description locale="ru_RU">Обертка для альбома фотографий</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Photos app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Фото»</description>
        </file>
        <file path="home.html" custom="0">
            <description locale="en_US">Wrapper for the main photo gallery homepage</description>
            <description locale="ru_RU">Обертка для главной страницы фотогалереи</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Photos app content</description>
            <description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Фото»</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content</description>
            <description locale="ru_RU">Содержимое информационной страницы</description>
        </file>
        <file path="photo.html" custom="0">
            <description locale="en_US">One photo and its details</description>
            <description locale="ru_RU">Просмотр фотографий по одной</description>
        </file>
        <file path="photos-thumbs.html" custom="0">
            <description locale="en_US">Photo list thumbnails view</description>
            <description locale="ru_RU">Список фотографий эскизами</description>
        </file>
        <file path="photos-plain.html" custom="0">
            <description locale="en_US">Photo list plain view</description>
            <description locale="ru_RU">Список фотографий «простыней»</description>
        </file>
        <file path="search.html" custom="0">
            <description locale="en_US">Wrapper for photo search (filtering) results, e.g. by tag or by rating</description>
            <description locale="ru_RU">Обертка для страницы поиска (фильтрации) фотографий, например, по тегу или автору</description>
        </file>

        <file path="mobile.photos.css" custom="0">
        </file>
        <file path="mobile.photos.js" custom="0">
        </file>

        <file path="error.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="index.html" parent="1">
        </file>
        <file path="layout-head.html" parent="1">
        </file>
        <file path="layout-header.html" parent="1">
        </file>
        <file path="layout-menu.html" parent="1">
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="mobile.css" parent="1">
        </file>
        <file path="mobile.js" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
]]>
    </about>
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/sidebar/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="sidebar" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:sidebar" version="2.1.10">
    <name locale="en_US">Sidebar 2.0</name>
    <name locale="ru_RU">Sidebar 2.0</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="sidebar.css" custom="0" parent="1">
        </file>
        <file path="sidebar.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="sidebar.blog.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="main.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
            <description locale="ru_RU">Основной макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Blog app's &lt;head&gt; instructions</description>
            <description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="post.album.html" custom="0">
            <description locale="en_US">Photo album attached to the blog post</description>
            <description locale="ru_RU">Фотоальбом, прикрепленный к записи в блоге</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="nav.sidebar.html" custom="0">
            <description locale="en_US">Internal app navigation tree</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">Customer account navigation menu</description>
            <description locale="ru_RU">Меню навигации в личном кабинете покупателя</description>
        </file>
        <file path="login.html" parent="1">
        </file>
        <file path="signup.html" parent="1">
        </file>
        <file path="forgotpassword.html" parent="1">
        </file>
        <file path="my.profile.html" parent="1">
        </file>
        <file path="error.html" parent="1">
        </file>
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>Sidebar</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Sidebar theme for the Site application. All Sidebar design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
<p>Sidebar design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p><b>Sidebar</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Sidebar для приложения «Сайт» (данная тема). Все темы дизайна Sidebar для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
<p>Темы дизайна семейства Sidebar оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
]]>
    </about>    
</theme>

=== webasyst/webasyst-framework/wa-apps/blog/themes/vk/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="vk" system="0" vendor="webasyst" author="Webasyst" app="blog" parent_theme_id="site:vk" version="1.1.0">
    <name locale="en_US">VK</name>
    <name locale="ru_RU">Вконтакте</name>
    <files>
        <file path="index.html" custom="0" parent="1">
        </file>
        <file path="vk.css" custom="0" parent="1">
        </file>
        <file path="vk.js" custom="0" parent="1">
        </file>        
        <file path="vk.blog.css" custom="0">
            <description locale="en_US">Core Blog app CSS</description>
            <description locale="ru_RU">Основной CSS приложения «Блог»</description>
        </file>      
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout and navigation for the Blog app content</description>
			<description locale="ru_RU">Основное макет вывода содержимого и навигации в приложении «Блог»</description>
        </file>
        <file path="head.html" custom="0">
			<description locale="en_US">Blog app's &lt;head&gt; instructions</description>
			<description locale="en_US">Блок &lt;head&gt; приложения «Блог»</description>
        </file>
        <file path="stream.html" custom="0">
            <description locale="en_US">Post stream wrapper</description>
            <description locale="ru_RU">Обертка для страницы вывода списка записей</description>
        </file>
        <file path="stream_search.html" custom="0">
            <description locale="en_US">Post search (filtering) results, e.g. custom search, by tag, by author</description>
            <description locale="ru_RU">Результат поиска (фильтрации) записей, например, по тегу или автору</description>
        </file>
        <file path="stream_posts.html" custom="0">
            <description locale="en_US">Default post list view mode</description>
            <description locale="ru_RU">Основной вид списка записей блога</description>
        </file>
        <file path="post.html" custom="0">
            <description locale="en_US">Dedicated post page</description>
            <description locale="ru_RU">Страница одной записи блога</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static info page</description>
            <description locale="ru_RU">Информационная страница</description>
        </file>
        <file path="comments.html" custom="0">
            <description locale="en_US">Post comment list</description>
            <description locale="ru_RU">Комментарии к записи блога</description>
        </file>
        <file path="comment.html" custom="0">
            <description locale="en_US">One comment template</description>
            <description locale="ru_RU">Вывод одного комментария из списка</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
        <file path="navigation.html" custom="0">
            <description locale="en_US">Internal app navigation</description>
            <description locale="ru_RU">Внутренняя навигация приложения</description>
        </file>
    	<file path="footer.html" custom="0">
    		<description locale="en_US">App specific footer content</description>
    		<description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
    		<description locale="en_US">Internal app search form</description>
    		<description locale="ru_RU">Форма поиска в приложении</description>
        </file> 
    </files>
    <about locale="en_US">
<![CDATA[
<p><b>VK</b> design themes are designed for embedding Webasyst-powered websites into <a href="http://vk.com">VK.com</a> social network as iframe apps. VK theme family is universal — there is a theme for every basic Webasyst app: Site, Blog, Photos, Shop-Script, etc. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the VK theme for the Site application. All VK design themes for other apps (e.g., Blog or Photos) link common CSS and index.html layout file from the main theme.</p>
]]>
    </about>
    <about locale="ru_RU">
<![CDATA[
<p>Темы <b>VK</b> разработаны для внедрения сайтов, созданных на основе фреймворка Вебасист, в соцсеть «<a href="http://vk.com">Вконтакте</a>» в виде iframe-приложений. Семейство тем VK универсальное — подходит для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема для приложения «Сайт». Все темы VK для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
]]>
    </about>    
</theme>

=== webasyst/webasyst-framework/wa-apps/site/themes/clear/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE theme PUBLIC "wa-app-theme" "http://www.webasyst.com/wa-content/xml/wa-app-theme.dtd">
<theme id="clear" system="0" vendor="webasyst" author="Webasyst" app="site" version="1.2.18">
    <name locale="en_US">Clear</name>
    <name locale="ru_RU">Clear</name>
    <description locale="ru_RU">Семейство адаптивных тем дизайна.</description>
    <files>
        <file path="index.html" custom="0">
            <description locale="en_US">Core layout of the Clear theme family</description>
            <description locale="ru_RU">Основной макет тем дизайна семейства Clear</description>
        </file>
        <file path="clear.css" custom="0">
            <description locale="en_US">Core CSS of the Clear theme family</description>
            <description locale="ru_RU">Основной файл CSS-стилей семейства тем дизайна Clear</description>
        </file>
        <file path="clear.js" custom="0">
            <description locale="en_US">JS</description>
            <description locale="ru_RU">JS</description>
        </file>
        <file path="content.html" custom="0">
            <description locale="en_US">Main layout for the Site app content</description>
            <description locale="ru_RU">Основной вывод приложения «Сайт»</description>
        </file>
        <file path="head.html" custom="0">
            <description locale="en_US">Site app's &lt;head&gt; instructions</description>
            <description locale="ru_RU">Блок &lt;head&gt; приложения «Сайт»</description>
        </file>
        <file path="footer.html" custom="0">
            <description locale="en_US">App specific footer content</description>
            <description locale="ru_RU">Содержимое футера приложения</description>
        </file>
        <file path="searchform.html" custom="0">
            <description locale="en_US">Internal app search form</description>
            <description locale="ru_RU">Форма поиска в приложении</description>
        </file>
        <file path="page.html" custom="0">
            <description locale="en_US">Static page content and navigation</description>
            <description locale="ru_RU">Содержимое открытой страницы и навигация по страницам</description>
        </file>
        <file path="login.html" custom="0">
            <description locale="en_US">Login page</description>
            <description locale="ru_RU">Страница входа для пользователей</description>
        </file>
        <file path="signup.html" custom="0">
            <description locale="en_US">Sign up page</description>
            <description locale="ru_RU">Страница регистрации пользователей</description>
        </file>
        <file path="forgotpassword.html" custom="0">
            <description locale="en_US">Forgot password page</description>
            <description locale="ru_RU">Страница сброса пароля</description>
        </file>
        <file path="my.profile.html">
            <description locale="en_US">My profile: contact info editing form</description>
            <description locale="ru_RU">Мой профиль: редактирование контактной информации</description>
        </file>
        <file path="my.nav.html">
            <description locale="en_US">My profile navigation</description>
            <description locale="ru_RU">Навигационное меню внутри личного кабинета</description>
        </file>
        <file path="error.html" custom="0">
            <description locale="en_US">404 and other errors</description>
            <description locale="ru_RU">404 и другие ошибки</description>
        </file>
    </files>
    <about locale="en_US">
        <![CDATA[
        <p><b>Clear</b> is a universal adaptive design theme family for all basic Webasyst apps: Site, Blog, Photos, Shop-Script, and others. The parent (main) theme of the family, which includes the basic set of CSS rules and the common layout template index.html, is the Clear (i.e. this) theme for the Site application. All Clear design themes used in other applications (e.g., Blog or Photos) link common CSS and index.html layout file from the main (i.e. this) theme.</p>
        <p>Clear design themes automatically link CSS depending on a visitor's device. Supported devices and platforms: iOS or Android based mobile devices, tablet computers such as iPad, common desktop computers and laptops.</p>
        ]]>
    </about>
    <about locale="ru_RU">
        <![CDATA[
        <p><b>Clear</b> — это универсальное семейство адаптивных тем дизайна для всех базовых приложений фреймворка Вебасист: Сайт, Блог, Фото, Shop-Script и других. Родительской (основной) темой семейства, включающей в себя базовый набор CSS-стилей и общий макет дизайна index.html, является тема Clear для приложения «Сайт» (данная тема). Все темы дизайна Clear для других приложений (Блог, Фото и других) используют базовый CSS и index.html из родительской (основной) темы.</p>
        <p>Темы дизайна семейства Clear оптимизированы для всех современных браузеров, планшетных компьютеров и мобильных устройств на основе iOS и Android. CSS-стили подключаются в зависимости от разрешения и типа устройства, которым пользуется посетитель сайта.</p>
        ]]>
    </about>
    <settings>
        <setting var="footer_notice" control_type="text">
            <value></value>
            <name locale="en_US">Footer notice</name>
            <name locale="ru_RU">Уведомление в подвале сайта</name>
        </setting>
        <setting var="use_shop_schedule" control_type="checkbox">
            <value>1</value>
            <name locale="ru_RU">Показывать график работы магазина на текущую неделю из настроек Shop-Script</name>
            <name locale="en_US">Show online store’s working schedule for current week from Shop-Script settings</name>
            <description locale="ru_RU">При включении игнорируется настройка «Сокращенный график работы».</description>
            <description locale="en_US">When enabled, “Brief working schedule” setting is ignored.</description>
        </setting>
        <setting var="manual_schedule" control_type="text">
            <value></value>
            <name locale="ru_RU">Сокращенный график работы</name>
            <name locale="en_US">Brief working schedule</name>
            <description locale="ru_RU">Например: Пн—Сб 08:00–18:00</description>
            <description locale="en_US">Example: Mo—Sa 08:00–18:00</description>
        </setting>
    </settings>
</theme>
